### ISSUE TITLE
CDN not available

### ISSUE THREAD

**Issue by mroeling** [phensley/cldr-engine#10]
![image](https://github.com/phensley/cldr-engine/assets/2706186/6f496de3-1392-4cd5-b028-773a3a1337cd)

Is there an alternative location available for the language files please?

**Comment by mroeling** [comment]
Extra info: it looks like the CDN uses a CloudFlare certificate, which fails atm. 
Trying to reach the data from The Netherlands, through AWS eu-west-1 VPN.

**Comment by phensley** [comment]
The CDN issue is known by jsdelivr and is being tracked here https://github.com/jsdelivr/jsdelivr/issues/18565
