### ISSUE TITLE
Date/Number parsing

### ISSUE THREAD

**Issue by maertz** [phensley/cldr-engine#7]
Hi there, I was just wondering if there are any plans to add parsing to the feature stack. In some scenarios it would be nice to parse the date or number against the current user culture.

Regards
Benjamin

**Comment by phensley** [comment]
hi @maertz  I don't currently have plans to add parsing of dates or numbers. 

The globalize library contains parsers for [dates](https://github.com/globalizejs/globalize/blob/master/doc/api/date/date-parser.md) and [numbers](https://github.com/globalizejs/globalize/blob/master/doc/api/number/number-parser.md) which could be adapted or reimplemented by someone to use cldr-engine schema and data. I'm not sure how well those parsers work in practice, but they seem geared towards strict parsing where the date/number pattern is known in advance.
